version: '3.8'

services:
  app:
    build: .
    restart: always
    environment:
      - AWS_REGION=${AWS_REGION}
    networks:
      - book-network

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - book-network

networks:
  book-network: